version: "3"

services:
  jira:
    image: eugenmayer/jira
    container_name: jira
    ports:
      - '80:8080'
    environment:
      JIRA_DATABASE_URL: mysql://jiradb@db/jiradb
      # since we run against mysql5.7 - below that set to mysql
      JIRA_MYSQL_DB_VERSION: mysql57
      # for mysql up to 5.6
      #- 'JIRA_MYSQL_DB_VERSION=mysql
      JIRA_DB_PASSWORD: jellyfish
      # need for the wait-for-db statement
      JIRA_DB_HOST: db
      JIRA_DB_PORT: 5432
  db:
    image: mysql:5.7
    environment:
      - 'MYSQL_ROOT_PASSWORD=verybigsecretrootpassword'
      - 'MYSQL_DATABASE=jiradb'
      - 'MYSQL_USER=jiradb'
      - 'MYSQL_PASSWORD=jellyfish'
